### ISSUE TITLE
SAPI functionality is broken

### ISSUE THREAD

**Issue by bmustill-rose** [nstockton/speechlight#2]
SAPI functionality doesn't appear to be working under Windows 10 21H2 and Python 3.10.4 using speechlight 1.7.2. The issue is also present in 1.6.2. (Unfortunately I don't have access to any other Windows versions to test at the moment).

I'm testing using the below:

1. Write a script similar to the below.
```python
from speechlight import speech

speech.output("Hello world!")
```
2. Exit all screen readers.
3. Run the script.
4. Observe that nothing is spoken and no errors are printed.

My understanding is that SL should default to SAPI when no other screen readers are running but this appears not to be the case.

Thanks.

**Comment by nstockton** [comment]
Should be fixed now. Thanks for reporting.
